### ISSUE TITLE
Add Sentry logging

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/ext-theme#402]
The integration with Sentry is very minor:

https://docs.sentry.io/platforms/javascript/guides/node/install/esm/

The configuration at Sentry and getting some of the noise out of the way might be more difficult, but hard to say until we do try this.

**Comment by agjohnson** [comment]
I tried this one quickly and got a pile of exceptions:

```
[webpack-dev-server] ERROR in node:zlib
Module build failed: UnhandledSchemeError: Reading from "node:zlib" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at /usr/src/app/checkouts/ext-theme/node_modules/webpack/lib/NormalModule.js:838:25
    at Hook.eval [as callAsync] (eval at create (/usr/src/app/checkouts/ext-theme/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
```

I think this might be Sentry has incompatibility with Webpack 5?

**Comment by agjohnson** [comment]
Ah! I was using the recommended `@sentry/node` but should have been using `@sentry/browser` instead. I no longer get and errors, but Sentry doesn't seem to log anything still. I'm guessing I don't have it configured.
